### ISSUE TITLE
cant build new html sites

### ISSUE THREAD

**Issue by pvtex** [omersiar/esp-rfid#637]
When i start the builder.exe to generate the compressed webfiles i get this error:

```
C:\Users\USER\Documents\ESP-RFID\tools\webfilesbuilder>builder.exe
[23:02:15] Using gulpfile ~\Documents\ESP-RFID\tools\webfilesbuilder\gulpfile.js
C:\snapshot\webfilesbuilder\node_modules\gulp\bin\gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                   ^

TypeError: Cannot read property 'apply' of undefined
    at C:\snapshot\webfilesbuilder\node_modules\gulp\bin\gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1310:13)
    at startup (bootstrap_node.js:227:16)
    at bootstrap_node.js:648:3
```

**Comment by pvtex** [comment]
can anybody help?
i need to add a new menu item for a new feature

**Comment by pvtex** [comment]
could fix it by editing the package.json file.

```
{
  "name": "uglifier",
  "version": "0.0.1",
  "description": "Combine all js and css files into one and gzip them for the ESP-RFID project",
  "main": "unglify.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "gulp"
  },
  "author": "ESP-RFID Developers",
  "license": "UNLICENSED",
  "dependencies": {
    "gulp": "^3.9.1",
    "gulp-concat": "^2.6.1",
    "gulp-flatmap": "^1.0.2",
    "gulp-gzip": "^1.4.2",
    "gulp-htmlmin": "^4.0.0",
    "gulp-uglify": "^3.0.1",
    "pump": "^3.0.0"
  },
  "bin": "node_modules\\gulp\\bin\\gulp.js"
}
```

**Comment by pvtex** [comment]
fixed

**Comment by pvtex** [comment]
fixed
