### ISSUE TITLE
Compiling latest v.6 release with VSCode PIO

### ISSUE THREAD

**Issue by akeilox** [omersiar/esp-rfid#78]
Under Win10 x64, I could just download v0.5beta release, unzip, open with VSCode PIO and it compiles without any changes.

If I download the v0.6 release stable, unzip, open with VSCode PIO it doesnt comply, complaining about dependencies.

Is there a trick to get v0.6 to compile, noticed the platform.ini is difference between that versions, like v.05beta have declaration lib_deps_external = ....

Any pointers to get it compile would be appreciated.

**Comment by omersiar** [comment]
Try `pio update`

**Comment by akeilox** [comment]
i get the following when i try that on .6 stable (it compiles ok on .5beta)

`PS D:\_Development\esp-rfid-stable> pio update
Traceback (most recent call last):
  File "C:\Users\acm\.platformio\penv\Scripts\pio-script.py", line 11, in <module>
    load_entry_point('platformio==3.5.2rc4', 'console_scripts', 'pio')()
  File "c:\users\acm\.platformio\penv\lib\site-packages\platformio\__main__.py", line 123, in main
    maintenance.on_platformio_exception(e)
  File "c:\users\acm\.platformio\penv\lib\site-packages\platformio\maintenance.py", line 64, in on_platformio_exception
    telemetry.on_exception(e)
  File "c:\users\acm\.platformio\penv\lib\site-packages\platformio\telemetry.py", line 347, in on_exception
    mp = MeasurementProtocol()
  File "c:\users\acm\.platformio\penv\lib\site-packages\platformio\telemetry.py", line 66, in __init__
    self['cid'] = app.get_cid()
  File "c:\users\acm\.platformio\penv\lib\site-packages\platformio\app.py", line 350, in get_cid
    cid = get_state_item("cid")
  File "c:\users\acm\.platformio\penv\lib\site-packages\platformio\app.py", line 292, in get_state_item
    with State() as data:
  File "c:\users\acm\.platformio\penv\lib\site-packages\platformio\app.py", line 91, in __init__
    self.path = join(util.get_home_dir(), "appstate.json")
  File "c:\users\acm\.platformio\penv\lib\site-packages\platformio\util.py", line 237, in get_home_dir
    join(expanduser("~"), ".platformio"))
  File "c:\users\acm\.platformio\penv\lib\site-packages\platformio\util.py", line 217, in get_project_optional_dir
    config = load_project_config()
  File "c:\users\acm\.platformio\penv\lib\site-packages\platformio\util.py", line 354, in load_project_config
    cp.read(path)
  File "c:\users\acm\.platformio\penv\lib\site-packages\backports\configparser\__init__.py", line 705, in read
    self._read(fp, filename)
  File "c:\users\acm\.platformio\penv\lib\site-packages\backports\configparser\__init__.py", line 1113, in _read
    fpname, lineno)
backports.configparser.DuplicateOptionError: While reading from 'D:\\_Development\\esp-rfid-stable\\platformio.ini' [line 38]: option u'build_flags' in section u'env:deploy' already exists`

**Comment by omersiar** [comment]
check Platformio.ini fle find 

build_flags under [env:deploy] delete both build_flags line, try pio update again.

**Comment by omersiar** [comment]
Did you managed to get it work?

**Comment by akeilox** [comment]
thanks @omersiar
two build_flags did the trick! I had to run pio update 2 times as it failed in 1st attempt; guessing while downloading stuff, switching alternate servers.

But the bottom line is commenting out the two build_flags lines under env:deploy
and pio update
solved the problem.

Can I say you have outdone yourself with the new UI and firmware upgrade, its really nice!

**Comment by omersiar** [comment]
There shouldn't be two build_flags in the first place, made changes, 

I guess you can say that though there is always space for improvement.

and also beta web demo is live here: http://37.148.209.63/esp-rfid/

**Comment by akeilox** [comment]
new web UI is fast! github connected firmware upgrade is simply great. 

For Event logs and User logs, I was thinking if it makes sense to expose a url (authenticated) endpoint where the logs can be fetched-and-cleared. In this way esp-rfid stays true to its vision as standalone, but enable large data handling/retention,  where remote agents can connect, retrieve and clear the log files.

In a scenario, one can write a script to connect to rfid-node  every week/month, fetch data (users, accesslog, eventlog) as JSON, and give clear command to clear the logs.

**Comment by omersiar** [comment]
This can be done like, today :) No need to expose a url, this can be done with a simple web socket client. You can start to code your script today with just node.js nothing else.
